# This environment file defines the dependencies for the datasetdocgen.py
# script.

name: deepesdl-doc
channels:
  - conda-forge
dependencies:
  - python >=3.9
  - click >=8.1
  - cartopy >=0.21.0
  - pyyaml >=6.0
  - xcube
  - tenacity