site_name: "DeepESDL"
site_url: "http://127.0.0.1:8000/"   # TODO!
copyright: Copyright (c) 2022 by the DeepESDL Team
theme: readthedocs
# theme: mkdocs

nav:
  - Home: user-guide.md

plugins:
  - search
  - mkapi

markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 2
  - attr_list
