site_name: DeepESDL Documentation
site_url: https://deepesdl.readthedocs.io
repo_url: https://github.com/deepesdl/deepesdl-doc
edit_uri: edit/main/docs
copyright: Copyright © 2022 by the DeepESDL Team
theme: readthedocs  # alternative: mkdocs

nav:
  - Home:
    - About DeepESDL: index.md
  - User guide:
    - Overview: guide/overview.md
    - JupyterLab: guide/jupyterlab.md
    - xcube Viewer: guide/xcube-viewer.md
    - Datacubes: guide/datacubes.md
    - Datacube generation: guide/datacube-generation.md
    - ML Toolkits: guide/ml-toolkits.md
    - Further information: guide/further-information.md
  - ML Toolkit:
    - Introduction: ml-toolkit/introduction.md
    - Getting Started: ml-toolkit/getting-started.md
    - Example Use Case: ml-toolkit/example.md
  - Datasets:
    - List of datasets: datasets/datasets.md
    - Earth System Data Cube: datasets/ESDC.md
    - Baltic Sea Cube: datasets/baltic-sea.md
    - Black Sea Cube: datasets/black-sea.md
    - Land Cover Cube: datasets/LC-1x2160x2160-1-0-0-zarr.md
    - Ocean Cube: datasets/ocean-1M-9km-1x1080x1080-1-4-0-zarr.md
    - SMOS freeze/thaw Cube: datasets/SMOS-snow-4267x10x10-1-0-1-zarr.md
  - Design:
    - Context: design/context.md
    - Architecture: design/architecture.md
    - Hub: design/hub.md
    - Services and Tools: design/services-and-tools.md

plugins:
  - search
  - mkapi

markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 2
  - attr_list
