site_name: DeepESDL
site_url: http://127.0.0.1:8000/
copyright: Copyright © 2022 by the DeepESDL Team
theme: readthedocs  # alternative: mkdocs

nav:
  - Home:
    - Index: index.md
  - User guide:
    - Index: guide/user-guide.md
  - Design:
    - Index: design/index.md
  - Datasets:
    - List of datasets: datasets/datasets.md
    - Earth System Data Cube: datasets/ESDC.md
    - Black Sea Cube: datasets/black-sea.md

plugins:
  - search
  - mkapi

markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 2
  - attr_list
