site_name: "DeepESDL"
site_url: "http://127.0.0.1:8000/"   # TODO!
copyright: Copyright (c) 2022 by the DeepESDL Team
theme: readthedocs
# theme: mkdocs

nav:
  - Home: index.md
  - User Guide: guide/user-guide.md
  - Design: design/index.md
  - Datasets:
    - Black sea: datasets/black-sea.md

plugins:
  - search
  - mkapi

markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 2
  - attr_list
